# -*- coding: utf-8 -*-
"""TransformersVit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqMkYgV2AHHdA4Sn0R2FOmlre2efqLHk
"""

import matplotlib.pyplot as plt
import torch
import torchvision


from torch import nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader , Subset

!pip install torchinfo
from torchinfo import summary

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"
device

device

IMG_SIZE = 224
seed = 42

def to_rgb(img):
  return img.convert("RGB")

train_tf = transforms.Compose([
    transforms.Lambda(to_rgb),
    transforms.RandomResizedCrop(IMG_SIZE,scale=(0.6,1.0), ratio=((0.75,1.33))),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=(-30, 30)),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.01),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])
test_tf = transforms.Compose([
    transforms.Lambda(to_rgb),
    transforms.Resize(256),
    transforms.CenterCrop(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])

from torch.utils.data import random_split
root = "./data"
test_ratio = 0.2

import os

# Check if `root` (./data) exists as a file and remove it if it does
if os.path.exists(root) and os.path.isfile(root):
    os.remove(root)

ds_train_full = datasets.Caltech101(root=root, download=True, transform=train_tf)
ds_test_full = datasets.Caltech101(root=root, download=True, transform=test_tf)

n_total = len(ds_train_full)
n_test = int(n_total * test_ratio)
n_train = n_total - n_test

perm = torch.randperm(n_total, generator=torch.Generator().manual_seed(seed)).tolist()

type(perm)

train_idx= perm[:n_train]
test_idx = perm[n_train:]

len(train_idx),len(test_idx)

train_ds = Subset(ds_train_full,train_idx)
test_ds = Subset(ds_test_full,test_idx)

BATCH_SIZE = 32

train_dataloader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
test_dataloader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)

ds_train_full.categories

class_names = ds_train_full.categories

height= 224
width = 224
color_channels = 3
patch_size = 16

number_of_patches = (height * width) / (patch_size **2)

number_of_patches

embedding_layer_input_shape = (height,width,color_channels)

print(embedding_layer_input_shape)

embedding_layer_output_shape = (number_of_patches,patch_size**2 * color_channels)

embedding_layer_output_shape

image , label =train_dataloader.dataset[31]

class_names[label]

image.shape

plt.imshow(image.permute(1,2,0))
plt.title(class_names[label])

age_permuted = image.permute(1, 2, 0)
img_size = 224
patch_size = 16
num_patches = img_size/patch_size
assert img_size % patch_size == 0, "Image size must be divisible by patch size"
print(f"Number of patches per row: {num_patches}\nNumber of patches per column: {num_patches}\nTotal patches: {num_patches*num_patches}\nPatch size: {patch_size} pixels x {patch_size} pixels")

# Create a series of subplots
fig, axs = plt.subplots(nrows=img_size // patch_size, # need int not float
                        ncols=img_size // patch_size,
                        figsize=(num_patches, num_patches),
                        sharex=True,
                        sharey=True)

# Loop through height and width of image
for i, patch_height in enumerate(range(0, img_size, patch_size)): # iterate through height
    for j, patch_width in enumerate(range(0, img_size, patch_size)): # iterate through width

        # Plot the permuted image patch (age_permuted -> (Height, Width, Color Channels))
        axs[i, j].imshow(age_permuted[patch_height:patch_height+patch_size, # iterate through height
                                        patch_width:patch_width+patch_size, # iterate through width
                                        :]) # get all color channels

        # Set up label information, remove the ticks for clarity and set labels to outside
        axs[i, j].set_ylabel(i+1,
                             rotation="horizontal",
                             horizontalalignment="right",
                             verticalalignment="center")
        axs[i, j].set_xlabel(j+1)
        axs[i, j].set_xticks([])
        axs[i, j].set_yticks([])
        axs[i, j].label_outer()

# Set a super title
fig.suptitle(f"{class_names[label]} -> Patchified", fontsize=16)
plt.show()

patch_size = 16
conv2d=nn.Conv2d(in_channels=3,
                 out_channels=768,
                 kernel_size=patch_size,
                 stride=patch_size,
                 padding=0)

image.shape

image_out_of_conv = conv2d(image)

image_out_of_conv.shape

image.shape

flatten = nn.Flatten(start_dim=1,end_dim=2)

image_out_of_conv_flattened = flatten(image_out_of_conv)

image_out_of_conv = conv2d(image.unsqueeze(0))

image_out_of_conv.shape

flatten = nn.Flatten(start_dim=2,end_dim=3)

image_out_of_conv_flattened = flatten(image_out_of_conv)

image_out_of_conv_flattened.shape

image_out_of_conv_flattened.permute(0,2,1).shape

class PatchEmbedding(nn.Module):
  def __init__(self,
               in_channels: int =3,
               embedding_dim: int = 768,
               patch_size : int = 16):
      super().__init__()

      self.patcher = nn.Conv2d(in_channels=in_channels,
                               out_channels=embedding_dim,
                               kernel_size=patch_size,
                               stride=patch_size,
                               padding=0)
      self.flatten = nn.Flatten(start_dim=2,end_dim=3)

  def forward(self,x):
    x_patcher = self.patcher(x)
    x_flattened = self.flatten(x_patcher)
    return x_flattened.permute(0,2,1)

patch_embedding = PatchEmbedding(in_channels=3,patch_size=16,embedding_dim=768)

patch_embedding_image = patch_embedding(image.unsqueeze(0))

random_input_image = (1,3,224,224)

summary(PatchEmbedding(),
        input_size=random_input_image,
        col_names = ["input_size","output_size","num_params","trainable"])

batch_size = patch_embedding_image.shape[0]

embedding_dimension = patch_embedding_image.shape[-1]

class_token = nn.Parameter(torch.ones(batch_size,1,embedding_dimension),requires_grad=True)
print(class_token.shape)

patch_embedding_image_with_class_embedding = torch.cat((class_token, patch_embedding_image),dim=1)

number_of_patches = int((height * width) / (patch_size **2))

embedding_dimension = patch_embedding_image_with_class_embedding.shape[-1]

position_embedding = nn.Parameter(torch.ones(1,number_of_patches + 1 ,embedding_dimension),requires_grad=True)

patch_and_position_embedding=patch_embedding_image_with_class_embedding + position_embedding

patch_size = 16
height,width = image.shape[1],image.shape[2]
x = image.unsqueeze(0)
print(f"input shape : {x.shape}")

patch_embedding_layer = PatchEmbedding(in_channels=3,patch_size=16,embedding_dim=768)

patch_embedding = patch_embedding_layer(x)
print(f"patch embedding shape : {patch_embedding.shape}")

batch_size = patch_embedding.shape[0]
embedding_dimension = patch_embedding.shape[-1]

class_token = nn.Parameter(torch.randn(batch_size,1,embedding_dimension),requires_grad=True)

print(f"class token shape : {class_token.shape}")

patch_embedding_class_token = torch.cat((class_token, patch_embedding),dim=1)
print(f"patch embedding with class embedding shape : {patch_embedding_class_token.shape}")


number_of_patches = int((height * width) / (patch_size **2))
embedding_dimension = patch_embedding_class_token.shape[-1]

position_embedding = nn.Parameter(torch.randn(1,number_of_patches + 1 ,embedding_dimension),requires_grad=True)

print(f"position embedding shape : {position_embedding.shape}")

patch_and_position_embedding=patch_embedding_class_token + position_embedding

print(f"patch embedding with class embedding and position embedding shape : {patch_and_position_embedding.shape}")

class MultiheadSelfAttentionBlock(nn.Module):
  def __init__(self,embedding_dim : int = 768,
               num_heads : int = 12,
               attn_dropout: float = 0.0):
     super().__init__()
     self.layer_norm = nn.LayerNorm(normalized_shape=embedding_dim)
     self.multihead_attention = nn.MultiheadAttention(embed_dim=embedding_dim,
                                                      num_heads=num_heads,
                                                      dropout=attn_dropout,
                                                      batch_first=True)

  def forward(self,x):
      x = self.layer_norm(x)
      attn_output,_ = self.multihead_attention(query=x,key=x,value=x,need_weights = False)

      return attn_output

multihead_self_attention_block = MultiheadSelfAttentionBlock()

patched_image_through_msa_block = multihead_self_attention_block(patch_and_position_embedding)
print(f"patched image through msa block shape : {patched_image_through_msa_block.shape}")

class MLPBlock(nn.Module):
  def __init__(self,
               embedding_dim : int = 768,
               mlp_size : int = 3072,
               dropout : float = 0.1):
    super().__init__()
    self.layer_norm = nn.LayerNorm(normalized_shape=embedding_dim)
    self.mlp = nn.Sequential(
        nn.Linear(in_features=embedding_dim,out_features=mlp_size),
        nn.GELU(),
        nn.Dropout(p=dropout),
        nn.Linear(in_features=mlp_size,out_features=embedding_dim),
        nn.Dropout(p=dropout)
    )


  def forward(self,x):
    x = self.layer_norm(x)
    x = self.mlp(x)
    return x

mlp_block = MLPBlock()
patched_imaged_through_mlp_block = mlp_block(patched_image_through_msa_block)
print(f"patched image through mlp block shape : {patched_imaged_through_mlp_block.shape}")

class TransformerEncoderBlock(nn.Module):
  def __init__(self,
               embedding_dim : int = 768,
               num_heads : int = 12,
               mlp_size : int = 307,
               attn_dropout : float = 0.1,
               mlp_dropout : float = 0.1):
    super().__init__()
    self.msa_block = MultiheadSelfAttentionBlock(embedding_dim=embedding_dim,
                                                 num_heads=num_heads,
                                                 attn_dropout=attn_dropout)
    self.mlp_block = MLPBlock(embedding_dim=embedding_dim,
                              mlp_size=mlp_size,
                              dropout=mlp_dropout)

  def forward(self,x):
    x = x + self.msa_block(x)
    x = x + self.mlp_block(x)
    return x

transformer_encoder_block = TransformerEncoderBlock()

summary(model=transformer_encoder_block,
        input_size=[1,197,768],
        col_names=["input_size","output_size","num_params","trainable"])

class Vit(nn.Module):
  def __init__(self,
               patch_size : int = 16,
               image_size : int = 224,
               num_classes : int = 101,
               in_channels : int = 3,
               num_transformer_layer : int = 12,
               embedding_dim : int = 768,
               num_heads : int = 12,
               mlp_size : int = 307,
               attn_dropout : float = 0.1,
               mlp_dropout : float = 0.1):
    super().__init__()

    self.num_patches = number_of_patches =int((img_size* img_size) / (patch_size **2))
    self.class_embedding = nn.Parameter(torch.randn(1,1,embedding_dim),requires_grad=True)
    self.position_embedding = nn.Parameter(torch.randn(1,self.num_patches + 1 ,embedding_dim),requires_grad=True)
    self.patch_embedding = PatchEmbedding(in_channels=in_channels,
                                          patch_size=patch_size,
                                          embedding_dim=embedding_dim)
    self.transformer_encoder = nn.Sequential(
        *[TransformerEncoderBlock(embedding_dim=embedding_dim,
                                  num_heads=num_heads,
                                  mlp_size=mlp_size,
                                  attn_dropout=attn_dropout,
                                  mlp_dropout=mlp_dropout)
          for _ in range(num_transformer_layer)]
    )

    self.classifier = nn.Sequential(
        nn.LayerNorm(normalized_shape=embedding_dim),
        nn.Linear(in_features=embedding_dim,out_features=num_classes)
    )

  def forward(self,x):

    batch_size = x.shape[0]

    class_token = self.class_embedding.expand(batch_size,-1,-1)
    x = self.patch_embedding(x)
    x = torch.cat((class_token, x),dim=1)
    x = self.position_embedding + x
    x = self.transformer_encoder(x)
    x = self.classifier(x[:,0])

    return x

batch_size = 32
class_token_embedding_single = nn.Parameter(data=torch.randn(1,1,768))
class_token_embedding_batch = nn.Parameter(data=torch.randn(batch_size,1,768))

print(f"class token embedding single shape : {class_token_embedding_single.shape}")
print(f"class token embedding batch shape : {class_token_embedding_batch.shape}")

class_token_embedding_batch_expand = class_token_embedding_single.expand(batch_size,-1,-1)
print(f"class token embedding batch expand shape : {class_token_embedding_batch_expand.shape}")

def train_step(model: torch.nn.Module,
               dataloader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer,
               device: torch.device):
    # Put model in train mode
    model.train()

    # Setup train loss and train accuracy values
    train_loss, train_acc = 0, 0

    # Loop through data loader data batches
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # 1. Forward pass
        y_pred = model(X)

        # 2. Calculate  and accumulate loss
        loss = loss_fn(y_pred, y)
        train_loss += loss.item()

        # 3. Optimizer zero grad
        optimizer.zero_grad()

        # 4. Loss backward
        loss.backward()

        # 5. Optimizer step
        optimizer.step()

        # Calculate and accumulate accuracy metrics across all batches
        y_pred_class = torch.argmax(torch.softmax(y_pred, dim=1), dim=1)
        train_acc += (y_pred_class == y).sum().item() / len(y_pred)

    # Adjust metrics to get average loss and accuracy per batch
    train_loss = train_loss / len(dataloader)
    train_acc = train_acc / len(dataloader)
    return train_loss, train_acc


def test_step(model: torch.nn.Module,
              dataloader: torch.utils.data.DataLoader,
              loss_fn: torch.nn.Module,
              device: torch.device):
    # Put model in eval mode
    model.eval()

    # Setup test loss and test accuracy values
    test_loss, test_acc = 0, 0

    # Turn on inference context manager
    with torch.inference_mode():
        # Loop through DataLoader batches
        for batch, (X, y) in enumerate(dataloader):
            X, y = X.to(device), y.to(device)
            # 1. Forward pass
            test_pred_logits = model(X)

            # 2. Calculate and accumulate loss
            loss = loss_fn(test_pred_logits, y)
            test_loss += loss.item()

            # Calculate and accumulate accuracy
            test_pred_labels = test_pred_logits.argmax(dim=1)
            test_acc += ((test_pred_labels == y).sum().item() / len(test_pred_labels))

    # Adjust metrics to get average loss and accuracy per batch
    test_loss = test_loss / len(dataloader)
    test_acc = test_acc / len(dataloader)
    return test_loss, test_acc


def train(model: torch.nn.Module,
          train_dataloader: torch.utils.data.DataLoader,
          test_dataloader: torch.utils.data.DataLoader,
          optimizer: torch.optim.Optimizer,
          device: torch.device,
          loss_fn: torch.nn.Module = nn.CrossEntropyLoss(),
          epochs: int = 5):
    # 2. Create empty results dictionary
    results = {"train_loss": [],
               "train_acc": [],
               "test_loss": [],
               "test_acc": []
               }

    # 3. Loop through training and testing steps for a number of epochs
    for epoch in range(epochs):
        train_loss, train_acc = train_step(model=model,
                                           dataloader=train_dataloader,
                                           loss_fn=loss_fn,
                                           optimizer=optimizer,
                                           device=device)
        test_loss, test_acc = test_step(model=model,
                                        dataloader=test_dataloader,
                                        loss_fn=loss_fn,
                                        device=device)

        # 4. Print out what's happening
        print(
            f"Epoch: {epoch + 1} | "
            f"train_loss: {train_loss:.4f} | "
            f"train_acc: {train_acc:.4f} | "
            f"test_loss: {test_loss:.4f} | "
            f"test_acc: {test_acc:.4f}"
        )

        # 5. Update results dictionary
        # Ensure all data is moved to CPU and converted to float for storage
        results["train_loss"].append(train_loss.item() if isinstance(train_loss, torch.Tensor) else train_loss)
        results["train_acc"].append(train_acc.item() if isinstance(train_acc, torch.Tensor) else train_acc)
        results["test_loss"].append(test_loss.item() if isinstance(test_loss, torch.Tensor) else test_loss)
        results["test_acc"].append(test_acc.item() if isinstance(test_acc, torch.Tensor) else test_acc)

    # 6. Return the filled results at the end of the epochs
    return results

vit = Vit(num_classes=len(class_names)).to(device)

optimizer = torch.optim.Adam(params=vit.parameters(),lr=3e-3,weight_decay=0.3)

loss_fn = nn.CrossEntropyLoss()

from numpy.matrixlib import test
results = train(model=vit,
                train_dataloader=train_dataloader,
                test_dataloader=test_dataloader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                device= device,
                epochs= 10)

pretrained_vit_weights = torchvision.models.ViT_B_16_Weights.DEFAULT

pretrained_vit = torchvision.models.vit_b_16(weights=pretrained_vit_weights).to(device)

for parameter in pretrained_vit.parameters():
  parameter.requires_grad = False

pretrained_vit

pretrained_vit.heads = nn.Linear(in_features=768,out_features=len(class_names)).to(device)

pretrained_vit_transforms = pretrained_vit_weights.transforms()
print(pretrained_vit_transforms)

optimizer = torch.optim.Adam(params=pretrained_vit.parameters(),lr=3e-3)

loss_fn = nn.CrossEntropyLoss()

pretrained_vit_results = train(model=pretrained_vit,
                train_dataloader=train_dataloader,
                test_dataloader=test_dataloader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                device= device,
                epochs= 5)

from typing import List, Tuple
import matplotlib.pyplot as plt
from PIL import Image

def transform_predict(model: torch.nn.Module,
                        image_path: str,
                        class_names: List[str],
                        image_size: Tuple[int, int] = (224, 224),
                        transform: torchvision.transforms = None,
                        device: torch.device=device):

    img = Image.open(image_path)

    if transform is not None:
        image_transform = transform
    else:
        image_transform = transforms.Compose([
            transforms.Resize(image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225]),
        ])


    model.to(device)
    model.eval()
    with torch.inference_mode():
      transformed_image = image_transform(img).unsqueeze(dim=0)
      target_image_pred = model(transformed_image.to(device))

    target_image_pred_probs = torch.softmax(target_image_pred, dim=1)
    target_image_pred_label = torch.argmax(target_image_pred_probs, dim=1)
    plt.figure()
    plt.imshow(img)
    plt.title(f"Pred: {class_names[target_image_pred_label]} | Prob: {target_image_pred_probs.max():.3f}")
    plt.axis(False)

thy_path = "sample_data/thy.jpg"

transform_predict(model=pretrained_vit,
                  image_path=thy_path,
                  class_names=class_names,
                  device = device)

