# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYgJFf2HBNI4eP0SrwaELWVVvGXNMzB3
"""

import pandas as pd

import matplotlib.pyplot as plt
import torch
import torchvision


from torch import nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader , Subset

!pip install torchinfo
from torchinfo import summary

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"
device

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

df = pd.read_csv(url, sep='\t', header=None, names=['label_text', 'text'])


df['label'] = df['label_text'].map({'ham': 0, 'spam': 1})
df = df.head(500).copy()

print("Veri Seti Boyutu:", len(df))
print("\nİlk veri örneği:")
print("Metin:", df.iloc[0]['text'])
print("Etiket:", df.iloc[0]['label'], f"({df.iloc[0]['label_text']})")

PAD_ID = 0
UNK_ID = 1
CLS_ID = 2
SEP_ID = 3
word2idx = {"[PAD]": PAD_ID, "[UNK]": UNK_ID, "[CLS]": CLS_ID, "[SEP]": SEP_ID}

idx = 4
for text in df['text']:
    for word in text.lower().split():
        if word not in word2idx:
            word2idx[word] = idx
            idx += 1

print(f"Harika! Sözlüğümüz hazır. Toplam {len(word2idx)} farklı kelime öğrendik.")

MAX_LEN = 32

def tokenize_text(text,word2idx,max_len = MAX_LEN):

  words=text.lower().split()

  words = ["[CLS]"] + words[:max_len-2] + ["[SEP]"]
  token_ids = [word2idx.get(w, UNK_ID) for w in words]
  padding_length = max_len - len(token_ids)
  token_ids = token_ids + ([PAD_ID] * padding_length)

  return torch.tensor(token_ids, dtype=torch.long)

ornek_metin = "hello my friend"
print("Örnek Metin:", ornek_metin)
print("Tensör Çıktısı:", tokenize_text(ornek_metin, word2idx))

from torch.utils.data import Dataset, DataLoader

class BertDataset(Dataset):
    def __init__(self, dataframe, word2idx, max_len=32):
        self.data = dataframe
        self.word2idx = word2idx
        self.max_len = max_len

    def __len__(self):
      return len(self.data)

    def __getitem__(self, index):
      row = self.data.iloc[index]
      text = str(row['text'])
      label = row['label']

      input_ids = tokenize_text(text, self.word2idx, self.max_len)
      segment_ids = torch.zeros_like(input_ids)
      label_tensor = torch.tensor(label, dtype=torch.long)

      return input_ids, segment_ids, label_tensor

train_dataset = BertDataset(df, word2idx, max_len=MAX_LEN)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

for input_ids, segment_ids, labels in train_loader:
   print("\n--- İlk Paket (Batch) ---")
   print("Girdi Boyutu (Input IDs):", input_ids.shape)
   print("Segment Boyutu:", segment_ids.shape)
   print("Etiket Boyutu:", labels.shape)
   break

class BERTEmbedding(nn.Module):
    # hidden_size=768 (Makaledeki BERT-Base'in uzay boyutu)
    def __init__(self, vocab_size, max_len=32, hidden_size=768):
        super().__init__()

        # 1. Kelimelerin kendi anlamları (padding_idx=0 diyerek [PAD] token'ını boş bırakıyoruz)
        self.token_emb = nn.Embedding(vocab_size, hidden_size, padding_idx=0)

        # 2. Pozisyon (Sıra) vektörleri
        self.position_emb = nn.Embedding(max_len, hidden_size)

        # 3. Segment (Cümle) vektörleri (0 veya 1 olacağı için toplam 2 tür)
        self.segment_emb = nn.Embedding(2, hidden_size)

        # Normalizasyon (LayerNorm) ve Ezber önleyici (Dropout)
        self.norm = nn.LayerNorm(hidden_size)
        self.dropout = nn.Dropout(0.1)

    def forward(self, input_ids, segment_ids):
        # input_ids boyutu: [batch_size, max_len] -> (Bizim örnekte [16, 32])
        seq_length = input_ids.size(1)

        # 0'dan 31'e kadar pozisyon ID'leri üretiyoruz (Cümledeki sırayı bilmesi için)
        position_ids = torch.arange(seq_length, dtype=torch.long, device=input_ids.device)
        position_ids = position_ids.unsqueeze(0).expand_as(input_ids)

        # 3 Farklı Embedding katmanından geçiriyoruz
        tokens = self.token_emb(input_ids)
        positions = self.position_emb(position_ids)
        segments = self.segment_emb(segment_ids)

        # MAKALEDEKİ O MEŞHUR "TOPLAMA" (SUMMING) İŞLEMİ
        x = tokens + positions + segments

        # Vektörü ehlileştir (Normalize et) ve dışarı yolla
        return self.dropout(self.norm(x))

# --- TEST ZAMANI ---
# Sözlüğümüzün boyutunu alıyoruz (Daha önce word2idx sözlüğünü doldurmuştuk)
vocab_size = len(word2idx)

# Modeli oluşturuyoruz
embedding_katmani = BERTEmbedding(vocab_size, max_len=MAX_LEN)

# DataLoader'dan gelen ilk paketi (input_ids ve segment_ids) bu katmana sokalım:
embeddings_cikti = embedding_katmani(input_ids, segment_ids)

print("Embedding Çıktı Boyutu:", embeddings_cikti.shape)
# Beklenen Çıktı: torch.Size([16, 32, 768])

import math
class MultiHeadAttention(nn.Module):
  def __init__(self, hidden_size= 768, num_heads=12):
    super().__init__()
    self.hidden_size = hidden_size
    self.num_heads = num_heads
    self.head_dim = hidden_size // num_heads

    self.q_linear = nn.Linear(hidden_size, hidden_size)
    self.k_linear = nn.Linear(hidden_size, hidden_size)
    self.v_linear = nn.Linear(hidden_size, hidden_size)

    self.out_linear = nn.Linear(hidden_size, hidden_size)
  def forward(self,x):
    batch_size , seq_length, _ = x.size()

    Q = self.q_linear(x)
    K = self.k_linear(x)
    V = self.v_linear(x)


    Q = Q.view(batch_size, seq_length, self.num_heads, self.head_dim)
    K = K.view(batch_size, seq_length, self.num_heads, self.head_dim)
    V = V.view(batch_size, seq_length, self.num_heads, self.head_dim)

    Q = Q.transpose(1, 2)
    K = K.transpose(1, 2)
    V = V.transpose(1, 2)

    scores = torch.matmul(Q, K.transpose(-2, -1))
    scores = scores / math.sqrt(self.head_dim)
    attention_weights = torch.softmax(scores, dim=-1)
    context = torch.matmul(attention_weights, V)
    context = context.transpose(1, 2).contiguous()
    context = context.view(batch_size, seq_length, -1)
    output = self.out_linear(context)
    return output

attention_katmani = MultiHeadAttention()
attention_cikti = attention_katmani(embeddings_cikti)
print("Attention'dan Çıkan Boyut:", attention_cikti.shape)

import torch
import torch.nn as nn
import torch.optim as optim

# ==========================================
# ADIM 7: FeedForward (Öğrenme Katmanı)
# ==========================================
# Attention'dan çıkan karmaşık bilgiyi kalıcı hafızaya kazıyan düz katman.
class FeedForward(nn.Module):
    def __init__(self, hidden_size=768, ff_hidden_size=3072):
        super().__init__()
        # 768 boyutunu alıp 4 katına (3072) genişletir (BERT makalesi kuralı)
        self.linear1 = nn.Linear(hidden_size, ff_hidden_size)
        self.gelu = nn.GELU() # ReLU yerine GELU kullanıyoruz (Yine makale kuralı)
        # Genişletilmiş veriyi tekrar 768'e daraltır
        self.linear2 = nn.Linear(ff_hidden_size, hidden_size)

    def forward(self, x):
        x = self.gelu(self.linear1(x))
        return self.linear2(x)

# ==========================================
# ADIM 8: Encoder Block (Tek Bir Transformer Makinesi)
# ==========================================
# Attention ve FeedForward'ı birleştirir ve aralarına LayerNorm/Dropout ekler.
class EncoderBlock(nn.Module):
    def __init__(self, hidden_size=768, num_heads=12):
        super().__init__()
        self.attention = MultiHeadAttention(hidden_size, num_heads)
        self.norm1 = nn.LayerNorm(hidden_size)
        self.dropout1 = nn.Dropout(0.1)

        self.feed_forward = FeedForward(hidden_size)
        self.norm2 = nn.LayerNorm(hidden_size)
        self.dropout2 = nn.Dropout(0.1)

    def forward(self, x):
        # 1. Kısım: Attention -> Dropout -> Residual(Kestirme) Ekleme -> Normalizasyon
        att_out = self.attention(x)
        x = self.norm1(x + self.dropout1(att_out)) # x + att_out mantığı (Skip Connection)

        # 2. Kısım: FeedForward -> Dropout -> Residual Ekleme -> Normalizasyon
        ff_out = self.feed_forward(x)
        x = self.norm2(x + self.dropout2(ff_out))
        return x

# ==========================================
# ADIM 9: Ana BERT Modeli Sınıfı (Büyük Birleştirme)
# ==========================================
class BERTClassifier(nn.Module):
    # num_layers=2 yapıyoruz. (Makaledeki BERT-Base 12'dir ama GPU yanmasın diye ödevde 2 katman yeter)
    def __init__(self, vocab_size, max_len=32, hidden_size=768, num_heads=12, num_layers=2, num_classes=2):
        super().__init__()
        # 1. Giriş Kapısı (Önceden yazdığımız Embedding)
        self.embedding = BERTEmbedding(vocab_size, max_len, hidden_size)

        # 2. Encoder Bloklarını Alt Alta Diziyoruz (ModuleList ile)
        self.encoder_blocks = nn.ModuleList([
            EncoderBlock(hidden_size, num_heads) for _ in range(num_layers)
        ])

        # 3. Sınıflandırma Kafası (Spam mi Değil mi?)
        # Modelden çıkan 768 boyutu alıp, num_classes (2) boyutuna düşürür.
        self.classifier = nn.Linear(hidden_size, num_classes)

    def forward(self, input_ids, segment_ids):
        # Kelimeleri vektöre çevir
        x = self.embedding(input_ids, segment_ids)

        # Vektörleri sırayla 2 adet Transformer bloğundan geçir
        for block in self.encoder_blocks:
            x = block(x)

        # SİHİRLİ NOKTA: Sadece [CLS] token'ının vektörünü alıyoruz.
        # [CLS] cümleye en başta (0. index) eklemiştik.
        # x'in boyutu [16, 32, 768]. Biz [16, 0, 768] olan yeri kesip alıyoruz.
        cls_output = x[:, 0, :]

        # CLS vektörünü sınıflandırıcıya sok ve spam(1)/normal(0) tahminini çıkar
        logits = self.classifier(cls_output)
        return logits


# ==========================================
# ADIM 10: EĞİTİM ŞALTERİNİ KALDIRIYORUZ! (Training Loop)
# ==========================================

# 1. Cihazı ayarla (GPU varsa ona geç)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Eğitim şu cihazda yapılıyor: {device}\n")

# 2. Modeli kur ve cihaza gönder
model = BERTClassifier(vocab_size=len(word2idx)).to(device)

# 3. Loss (Kayıp) ve Optimizer (Öğrenme Motoru) ayarları
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

# 4. Asıl Eğitim Döngüsü
epochs = 5
print("Eğitim Başlıyor...\n")

for epoch in range(epochs):
    model.train()
    total_loss = 0

    # DataLoader'dan paketleri sırayla al
    for batch_idx, (input_ids, segment_ids, labels) in enumerate(train_loader):
        # Verileri GPU'ya gönder
        input_ids = input_ids.to(device)
        segment_ids = segment_ids.to(device)
        labels = labels.to(device)

        # Modeli tahmin yapmaya zorla (İleri geçiş)
        optimizer.zero_grad()
        predictions = model(input_ids, segment_ids)

        # Tahminleri gerçek etiketlerle karşılaştırıp Loss (Hata) hesapla
        loss = criterion(predictions, labels)

        # Hatayı geriye yay (Backpropagation) ve ağırlıkları güncelle
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    # Her devirin (epoch) sonunda ortalama hatayı ekrana bas
    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{epochs} | Ortalama Loss (Hata): {avg_loss:.4f}")

print("\nVE İŞTE BU KADAR! BERT BAŞARIYLA EĞİTİLDİ!")

